config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dining_tables, :sections
  resources :reservations

  root 'welcome#index'

end

app/controllers/dining_tables_controller.rb
class DiningTablesController < ApplicationController

  before_action :load_sections
  before_action :load_dining_table, only: [:edit, :update, :destroy, :show]

  def index
    @dining_tables = DiningTable.includes(:section).order("created_at DESC").page(params[:page]).per(params[:per_page])
  end

  def new
    @dining_table = DiningTable.new
  end

  def create
    @dining_table = DiningTable.new(dining_table_params)
    if @dining_table.save
      redirect_to dining_tables_path, notice: "DiningTable added"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dining_table.update(dining_table_params)
      redirect_to dining_tables_path, notice: "DiningTable Updated"
    else
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if @dining_table.destroy
      redirect_to dining_tables_path, notice: "DiningTable entry deleted"
    else
      render :index
    end
  end

  protected

    def dining_table_params
      params.require(:dining_table).permit(:section_id, :no_of_seat, :status)
    end

    def load_dining_table
      @dining_table = DiningTable.find_by(id: params[:id])
      redirect_to dining_tables_path, notice: "Dining table Not found" unless @dining_table.present?
    end

    def load_sections
      @sections = Section.all
    end

end

app/views/dining_tables/_form.html.erb
<%= form_for @dining_table do |f|%>
  <div class="box-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Section</label>
      <%= f.select :section_id, options_for_select(@sections.collect{|i| [i.name,i.id]}, selected: @dining_table&.section_id),{}, class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">No. of Seat</label>
      <%= f.number_field :no_of_seat, placeholder: "No. of Seat", min: 2, max: 12, class: 'form-control'%>
    </div>
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <%= f.submit "Save", class: 'btn btn-primary'%>
  </div>
<%end%>

app/views/dining_tables/edit.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">Edit Table</h3>
      </div>
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/dining_tables/index.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">Table Listing</h3>
        <div class="box-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <%= link_to "Add New",new_dining_table_path, class: 'btn btn-xs btn-info'%>
          </div>
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody><tr>
            <th>Sr. NO. </th>
            <th>Section</th>
            <th>No. Of Seatings</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
          <%@dining_tables.each do |dining_table|%>
            <tr>
              <td><%= dining_table.id%></td>
              <td><%= dining_table.section_name%></td>
              <td><%= dining_table.no_of_seat%></td>
              <td><%= dining_table.status%></td>
              <td><%= link_to 'Edit', edit_dining_table_path(dining_table)%> | <%= link_to 'Delete', dining_table_path(dining_table), method: :delete%></td>
            </tr>
          <%end%>
        </tbody></table>
      </div>
      <div class="box-footer clearfix">
        <%=paginate @dining_tables%>
      </div>
    </div>
  </div>
</div>

app/views/dining_tables/new.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">Add Table</h3>
      </div>
      <%= render 'form'%>
    </div>
  </div>
</div>