config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dining_tables, :sections
  resources :reservations

  root 'welcome#index'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  acts_as_taggable
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  TYPES = ['OnlineReservation', 'PhoneReservation', 'WalkIn']
  RESERVATION_OVER = ['finished', 'cancel', 'noshow']
  OPEN_STATUS = [0,1,2]
  CLOSED_STATUS = [3,4,5]
  belongs_to :dining_table

  enum status: {booked: 0, arrived: 1, seated: 2, finished: 3, cancel: 4, noshow: 5}

  validates :customer_name, presence: true
  validates :customer_email, allow_blank: true , format: { with: VALID_EMAIL_REGEX }
  validates :customer_mobile, allow_blank: true, :numericality => true
  validates :booking_start_time, presence: true, :numericality => true
  validates :no_of_people, presence: true, :numericality => true
  validates :type, presence: true
  validate :set_booking_end_time, on: :create
  validates :booking_end_time, presence: true, :numericality => true
  validate :booking_start_time_should_be_current_time, on: :create #less than 10 mins
  validate :booking_start_time_should_be_less_than_booking_end_time
  validate :valid_no_of_people
  validate :table_is_available, on: :create

  before_save :set_finished_booking, on: :update

  scope :booking_start_between, -> (start_time, end_time) {where("booking_start_time>= ? and booking_start_time<= ?",start_time.to_i, end_time.to_i)}
  scope :booking_end_between, -> (start_time, end_time) {where("booking_end_time>= ? and booking_end_time<= ?",start_time.to_i, end_time.to_i)}
  scope :booking_starting_after_time, -> (start_time) {where("booking_start_time>?",start_time.to_i)}
  scope :booking_ending_before_time, -> (end_time) {where("booking_end_time<?",end_time.to_i)}
  scope :open_booking, -> {where(status: OPEN_STATUS)}
  scope :closed_booking, -> {where(status: CLOSED_STATUS)}

  #validate the booking start time
  def booking_start_time_should_be_current_time
    (((Time.now - 10.minute).to_i > booking_start_time) ? self.errors.add(:booking_start_time, "should be greater than current time") : true) if booking_start_time.present?
  end

  #validate if the bboked table is currently available or not
  def table_is_available
    unless DiningTable.available_table(start_time: booking_start_time, end_time: booking_end_time).pluck(:id).include? dining_table_id 
      self.errors.add(:dining_table_id, "is not available")
    end
  end

  #validate the booking start time should be less then end time
  def booking_start_time_should_be_less_than_booking_end_time
    ((booking_start_time > booking_end_time) ? self.errors.add(:booking_start_time, "should be less than booking end time") : true) if booking_start_time.present? and booking_end_time.present?
  end

  #validate the no.of people should less than equal to table capacity
  def valid_no_of_people
    (((self.dining_table&.no_of_seat || 0) >= (self.no_of_people || 0)) ? true : self.errors.add(:no_of_people, "cannot be accomadated in this table."))
  end

  #always set the end time as current time whenever the booking is finished/canclled/no_show
  def set_finished_booking
    if self.status_changed? and (RESERVATION_OVER.include? self.status)
      self.booking_end_time = Time.now.to_i
    end
  end

  #set the end time as +2hours then the booking start time ASSUMPTION
  def set_booking_end_time
    self.booking_end_time = (Time.at(booking_start_time) + 2.hours).to_i if booking_start_time.present?
  end

  #converting booking_start_time timestamp to datetime
  def start_time
    Time.at(booking_start_time)
  end

  #converting booking_end_time timestamp to datetime
  def end_time
    Time.at(booking_end_time)
  end

  #shorthand
  def table_name
    self.dining_table_id.to_s + "-" + self.dining_table.section_name
  end

  class << self
    #TBD need to figure out to chain the scopes
    def search(params)
      return booking_starting_after_time(DateTime.parse_time_default(params['start_time'])) if params['start_time'].present?
      return booking_ending_before_time(DateTime.parse_time_default(params['end_time'])) if params['end_time'].present?
      return open_booking if params['open'] == 'true'
      return close_booking if params['close'] == 'true'
    end

  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :load_available_tables, only: [:new, :edit]
  before_action :load_reservation, only: [:edit, :update, :destroy]

  def index
    if params[:search].present?
      @reservations = Reservation.search(params[:search]).page(params[:page]).per(params[:per_page])
    else
      @reservations = Reservation.order("booking_start_time desc").page(params[:page]).per(params[:per_page])
    end
    respond_to do |format|
      format.html
      format.json {render json: @reservations.to_json(only: [:id, :customer_name, :customer_email, :customer_mobile, :no_of_people, :status, :type] , methods: [:start_time, :end_time, :table_name])}
    end
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to reservations_path, notice: "Reservation added"
    else
      flash[:notice] = "Reservation not created"
      load_available_tables
      render :new
    end
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservations_path, notice: "Reservation Updated"
    else
      flash[:notice] = "Reservation not updated"
      load_available_tables
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if @reservation.destroy
      redirect_to reservations_path, notice: "Reservation entry deleted"
    else
      render :index
    end
  end

  protected

    def load_reservation
      @reservation = Reservation.includes(:dining_table).find_by(id: params[:id])
      redirect_to reservations_path, notice: "Reservation Not found" unless @reservation.present?
    end

    def load_available_tables
      @dining_tables = DiningTable.available_table
    end

    def reservation_params
      set_booking_start_time if params['reservation']['booking_start_time'].present?
      params.require(:reservation).permit(:type, :no_of_people, :booking_start_time, :booking_end_time, :dining_table_id, :customer_name, :customer_email, :customer_mobile)
    end

    def set_booking_start_time
      params['reservation']['booking_start_time'] = DateTime.parse_time_default(params['reservation']['booking_start_time']).to_i
    end

end

app/views/reservations/_form.html.erb
<%= form_for @reservation.becomes(Reservation) do |f|%>
  <div class="box-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Reservation Type</label>
      <%= f.select :type, options_for_select(Reservation::TYPES, selected: @reservation&.type),{}, class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Reservation Date Time</label>
      <%#= select_datetime(default_time(@reservation.booking_start_time), name: "booking")%>
      <%= f.text_field :booking_start_time, class: 'form-control datetimepicker', value: default_time(@reservation.booking_start_time)%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">No. Of Guests</label>
      <%= f.number_field :no_of_people, min: 1, max: 12, placeholder: 'Select No. of Guests', class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Table No.</label>
      <%= f.select :dining_table_id, options_for_select(@dining_tables.collect{|i| ["#{i.section_name}-#{i.id}", i.id]}, selected: @reservation&.dining_table_id),{}, class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Customer Name</label>
      <%= f.text_field :customer_name, placeholder: 'Enter Customer Name', class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Customer Email</label>
      <%= f.text_field :customer_email, placeholder: 'Enter Customer Email', class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Customer Phone No.</label>
      <%= f.text_field :customer_mobile, placeholder: 'Enter Customer Phone No.', class: 'form-control'%>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Tags</label>
      <%#= f.select :tags, options_for_select(Reservation::TYPES, selected: @reservation&.type),{}, class: 'form-control'%>
    </div>
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <%= f.submit "Save", class: 'btn btn-primary'%>
  </div>
<%end%>

app/views/reservations/edit.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">Edit Reservation</h3>
      </div>
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">Reservation Listing</h3>
        <div class="box-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <%= link_to "Add Reservation",new_reservation_path, class: 'btn btn-xs btn-info'%>
          </div>
        </div>
      </div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody><tr>
            <th> ID</th>
            <th>Table No. </th>
            <th>Customer Details</th>
            <th>No. Of Seatings</th>
            <th>Timing</th>
            <th>Booking Type</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
          <%@reservations.each do |reservation|%>
            <tr>
              <td><%= reservation.id%></td>
              <td><%= "#{reservation.dining_table_id} - #{reservation.dining_table.section_name}"%></td>
              <td><%= reservation.customer_name + " " + reservation.try(:customer_mobile) + " " + reservation.try(:customer_email)%></td>
              <td><%= reservation.no_of_people%></td>
              <td><%= Time.at(reservation.booking_start_time).strftime("%d/%m/%Y %H:%M") + " - " + Time.at(reservation.booking_end_time).strftime("%d/%m/%Y %H:%M")%></td>
              <td><%= reservation.type%></td>
              <td><%= reservation.status%></td>
              <td><%= link_to 'Edit', edit_reservation_path(reservation)%> | <%= link_to 'Delete', reservation_path(reservation), method: :delete%></td>
            </tr>
          <%end%>
        </tbody></table>
      </div>
      <div class="box-footer clearfix">
        <%=paginate @reservations%>
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <div class='box box-primary'>
      <div class='box-header with-border'>
        <h3 class="box-title">New Reservation</h3>
      </div>
      <%= render 'form'%>
    </div>
  </div>
</div>