config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dining_tables, :sections
  resources :reservations

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_time(booking_start_time)
    time = (booking_start_time.present? ? Time.at(booking_start_time) : Time.now)
    time.strftime('%d/%m/%Y %H:%M')
  end
end

app/views/application/_breadcrumbs.html.erb
<section class="content-header">
  <h1>
    Widgets
    <small>Preview page</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Widgets</li>
  </ol>
</section>

app/views/application/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  <strong>Copyright &copy; 2018 <a href="https://github.com/sagar18041">Sagar Patil</a>.</strong> All rights
  reserved.
</footer>

app/views/application/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <%=link_to root_path, class: "logo" do%>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
  <%end%>
  <!-- Header Navbar: style can be found in header.less -->
  <%= render 'navbar'%>
</header>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  </a>
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- Messages: style can be found in dropdown.less-->
      <li class="dropdown messages-menu">
      </li>
      <!-- Notifications: style can be found in dropdown.less -->
      <li class="dropdown notifications-menu">
      </li>
      <!-- Tasks: style can be found in dropdown.less -->
      <li class="dropdown tasks-menu">
      </li>
      <!-- User Account: style can be found in dropdown.less -->
      <li class="dropdown user user-menu">
      </li>
      <!-- Control Sidebar Toggle Button -->
      <li>
      </li>
    </ul>
  </div>
</nav>

app/views/application/_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Alexander Pierce</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="">
        <%= link_to dining_tables_path do%>
          <i class="fa fa-dashboard"></i> <span>Tables</span>
        <%end%>
      </li>
      <li class="">
        <%= link_to reservations_path do%>
          <i class="fa fa-dashboard"></i> <span>Reservations</span>
        <%end%>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>